trigger:
  batch: true
  branches:
    include:
      - master
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - master
      - stable-*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: sleep 180
    displayName: Sleep

